name = "pawnnexus-api-dev"
main = "src/index.ts"
compatibility_date = "2026-06-29"

[[d1_databases]]
binding = "DB"
database_name = "pawnnexus-dev"
database_id = "0b9db12e-4af8-452e-aef9-ce5e55c0acd3"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "pawnnexus-images"

[vars]
APP_BASE_URL = "https://pawnnexus-dev.pages.dev"
EMAIL_FROM = "PawnNexus <noreply@pawnnexus.com>"
PUBLIC_IMAGE_BASE_URL = "https://images.example.com"
